language: python
python:
  - 2.6
  - 2.7
# command to install dependencies
install:
    - pip install -r requirements.txt --use-mirrors
    - pip install -r requirements-test.txt --use-mirrors
    - pip install coveralls --use-mirrors
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
    - python setup.py develop
script:
    - py.test -m 'not slowtest'
after_success:
    - coveralls